### ISSUE TITLE
Just bought your app and not working

### ISSUE THREAD

**Issue by djskype** [kzahel/jstorrent-legacy-app#3]
I just bought the app for my chromebook and I open it and all it says is "Loading..." in the top left corner. what do i do?

**Comment by kzahel** [comment]
Hmm sorry about that. You should be able to return it. You could open the
developer tools and send me the error text. Let me know if you need
directions to do that. It is not difficult

**Comment by djskype** [comment]
there is no error message. it just says "loading..." and does nothing. How
do i go to developer tools?

**Comment by kzahel** [comment]
Here's how to see the error message
- load up app
- type chrome://inspect chrome://inspect/#apps into chrome url bar
- click "apps" on left.
- find JSTorrent (should be two, click the one that says grid.html next to
  it, not generated_background_page
- click on "inspect"
- send the error message that you see there

**Comment by tothlajos** [comment]
The same, I've just purchased it and it doesn't start...

it says "Loading..." 

I use Samsung Chrome.
Is there any fix for this problem? I wanna use torrents somehow

**Comment by kzahel** [comment]
Can you type "chrome://inspect" into your address bar, and inspect
JSTorrent page, and go to the "console" tab and see what error is printed
there? That will help me see what went wrong. Thanks!

**Comment by LSWSjr** [comment]
Mine displays the following:
X Uncaught TypeError: Cannot call method 'addListener' of undefined grid.is:1433
X Uncaught TypeError: Cannot read property 'identity' of undefined underscore.is:518
X Uncaught TypeError: Cannot call method 'queryUsageAndQuota' of undefined bittorrent.helpers.is:579

Hope that helps :)

Cheers
Rowan/LSWSjr

**Comment by kzahel** [comment]
Awesome. Thank you. Do you think you can possibly check one more thing?
Try typing "chrome.runtime.getManifest().version" into the console. Currently 5% of users are getting a different version, I need to know which one you are running.

**Comment by LSWSjr** [comment]
It gives the result: "0.4.1"

In other good news, the app has started running this morning without the error, and considering I'd just bought both the computer and your app yesterday part of me suspects it could be a problem with un-updated Chromebook software and not your app.

Cheers
Rowan/LSWSjr

**Comment by j1macon** [comment]
I've using the app for about a month, without incident. Loved it. Since you recently updated though, its not working on my Samsung chromebook. The app will load, BUT none of the buttons are functional.  Buttons don't do anything.  Please advise, thanks!  Below is the code (following instructions above).

Error in response to storage.get: Error: Invocation of form fileSystem.retainEntry(undefined) doesn't match definition fileSystem.retainEntry(object entry)
    at Object.<anonymous> (chrome-extension://anhdpjpojoipgpmfanmedjghaligalgb/js/collection.js:196:38) _generated_background_page.html:1

as for the version. It says 2.0.12.

**Comment by kzahel** [comment]
Thanks for the report. This happens when you hit "cancel" after selecting a
directory. You should be able to recover from this by selecting the
download directory from the options (don't hit cancel here) and then all
torrents will need to be reset (using the "More Actions"->Reset torrent
state) in the toolbar.

I have committed a fix and it will go out with the next update. (205cd882779ea5f7465057ce92b2fa1b7e7e6056)

If you are unable to make it work still, please let me know, and I will
push the update immediately.

**Comment by j1macon** [comment]
Thanks for the quick reply.  I tried options button, still no response.
I've got more actions and selected reset but nothing...  Any ideas why they
options function wind respond?  Any other suggestions?

**Comment by kzahel** [comment]
Okay, it looks like the problem was a little worse than I thought. I have another fix (5894602079e19105bcaee9529b246ea53a9a0f1d) that I am pushing to you now. You should get the update to 2.0.13 within an hour? I'm not sure how long it takes for google to push out an update to you. You can probably speed it up by clicking on "Developer" in chrome://extensions and then there's a button "check for updates now"

**Comment by j1macon** [comment]
Works beautifully again... thanks for all you do!
