### ISSUE TITLE
Disk Space issue

### ISSUE THREAD

**Issue by keving139** [kzahel/jstorrent-legacy-app#4]
The disk space seems really low.  When I first used your app it was 1 GB now it is 400 MB.  Do you know how I can increase it back to 1 GB.  I have clean the disk space on the app, and the disk usage is at 0.00 but it still is around 400 MB.

**Comment by kzahel** [comment]
I also had this problem on my samsung chromebook. The sandbox filesystem to
which files are downloaded is shared between other apps, so perhaps power
washing your device would work.

I'm working on an improvement that makes jstorrent download directly to
your hard disk instead of to the "sandbox" which should make this problem
go away. stay tuned...

**Comment by kzahel** [comment]
The new version is available and there are no limits (except how much physical disk space you have!)
