### ISSUE TITLE
error persisting piece: InvalidStateError

### ISSUE THREAD

**Issue by kaushik1618** [kzahel/jstorrent-legacy-app#46]
I started using jstorrent (downloaded the zip archive and loaded unpacked extension into Chrome browser on my Chromebox) yesterday and have run into this problem.

If I stop and start the torrent, it starts downloading for a while before encountering this same error again, stalling the progress of this torrent forever. I think this is a problem with writing the buffered downloaded pieces into the USB drive which is the destination for this torrent. It is ~78% complete but has stopped there with this error for some reason.

![screenshot](https://cloud.githubusercontent.com/assets/773302/3381057/702a7446-fc14-11e3-85a8-3cd0fbf8e2c1.png)

Any help?

**Comment by kaushik1618** [comment]
I've checked that I have enough disk space on both the Chromebox's internal SSD as well as the external USB stick to which the torrent is being downloaded.

**Comment by kaushik1618** [comment]
I have a hypothesis but I am not sure whether it is the root cause of this error. I just noticed that one of the files in this torrent has a total size of 4.09GB, of which exactly 4.00GB have already been downloaded. The external USB stick is a FAT32 partition which I believe has a file size limit of exactly 4GB. Whenever jstorrent downloads another piece of this large file and tries to write this to the USB stick, it is unable to do so due to exceeding the FAT32 file size limit and the write fails.

**Comment by kzahel** [comment]
So I like your idea that it's an error with the FAT32 maximum filesize, however I am not sure this is the root issue, because when it downloads, it does not allocate the full size of the file, like uTorrent etc do, but the file grows as you download more. But you said it got to 78%, so perhaps this is the issue.

I've actually never tested downloading a torrent file that large, so it could be some kind of issue with Chrome/ChromeOS. If you want, you could share the torrent file with me at graehlarts@gmail.com and I could see if I'm able to reproduce the error

**Comment by kaushik1618** [comment]
It was the FAT32 file size limit. I restarted the torrent with the internal SSD as the destination and the torrent completed without any issues. So it wasn't Chrome/ChromeOS, it was the external USB stick probably because it was FAT32. I think the internal SSD partition is ext4 or something like that.

**Comment by kzahel** [comment]
Cool. I will try and format a small USB drive and reproduce this error and then file a bug with google so that we can maybe get a better error message.

**Comment by will-ks** [comment]
Hi, I'm running in to the same issue, also using a FAT32 SD card, download stops at 4GB.
